### ISSUE TITLE
weird character error

### ISSUE THREAD

**Issue by julianfn20215** [BeroWasTaken/discord-welcome-with-image#1]
Hello very good, how could I correct this error so that it can allow rare characters also that the emojis can be seen
thank you!

https://i.imgur.com/CSykBBS.png

**Comment by bero-dev** [comment]
> Hello very good, how could I correct this error so that it can allow rare characters also that the emojis can be seen
> 
> thank you!
> 
> 
> 
> 
> 
> 
> 
> https://i.imgur.com/CSykBBS.png

Hi!
I think it's a problem with the Font being used. Try a different font and let me know if it worked!

**Comment by julianfn20215** [comment]
I tried multiple sources but that error keeps getting,

**Comment by julianfn20215** [comment]
> > Hola muy bien, como podria corregir este error para que pueda permitir caracteres raros tambien que se vean los emojis
> > ¡gracias!
> > https://i.imgur.com/CSykBBS.png
> 
> ¡Hola! Creo que es un problema con la fuente que se está utilizando. Pruebe con una fuente diferente y avíseme si funcionó.

Intenté varias fuentes, pero ese error sigue apareciendo,

¿Qué fuente recomiendas usar?

**Comment by julianfn20215** [comment]
Any solution?
